### ISSUE TITLE
Overlay is coming on top of Appbar

### ISSUE THREAD

**Issue by Lazeeez** [boyan01/overlay_support#83]
The overlay is coming on top of the appbar and the buttons in appbar are inaccessible because of that.

**To Reproduce**
1. Create a homepage and an appbar on top of it.
2. Provide an elevated button in the appbar.
3. Create an overlay screen on the same page using another elevated button.
4. Open the overlay you'll see that you wont be able to tap on the elevated button that you provided in the appbar.

This shouldnt be happening as appbar and child are two different component of scaffold.
  
**Expected behavior**
It is expected that the inaccessible area created from the overlay should just be contained in it parent container, in this case the body of scaffold and not on the appbar itself

**Screenshots**
![Screenshot 2022-10-03 at 11 23 33 AM](https://user-images.githubusercontent.com/64376519/193509692-e2b96805-0a0b-44ef-8323-b20110354414.png)
![Screenshot 2022-10-03 at 11 23 48 AM](https://user-images.githubusercontent.com/64376519/193509726-8b7b99f5-ec63-4699-a677-e585ffb64f5a.png)

as you can see in the above screenshots, 'Neo' is an elevated button but its not accessible as the overlay is creating an container on top of the entire page. 

**Version (please complete the following information):**
 - Flutter Version: Latest
 - OS: IOS
 - OverlaySupport Version : ^2.0.1

**Comment by boyan01** [comment]
this is the expected behivior, since the global overlay should on the top of all app widgets.

Maybe you can use `OverlaySupport.local` to achieve the desired effect.

1. use `OverlaySupport.local` to  warp  your body widget  in Scaffold.

https://github.com/boyan01/overlay_support/blob/cf782231bb51e5f5cc28d32622325b8661820286/lib/src/overlay_state_finder.dart#L63 

2.  call `showOverlay` with context parameter.

example: 

https://github.com/boyan01/overlay_support/blob/master/example/lib/pages/page_multi_overlay_support.dart

**Comment by Lazeeez** [comment]
It worked! thanks for the help @boyan01
